language: c
sudo: required
dist: xenial
compiler:
  - clang
  - gcc
script: ./autogen.sh -d && make && make check && sudo make check
before_install:
  - sudo apt-get update
  - sudo apt-get install -qq fuse libfuse-dev valgrind
  - sudo /bin/sh -c 'echo user_allow_other > /etc/fuse.conf'
  - sudo chmod 0777 /dev/fuse
  - sudo chmod 0777 /etc/fuse.conf
